import { FeatureGroup } from './FeaturesTable';

export const featuresList: FeatureGroup[] = [
  {
    name: 'Pulsar Resources Browser',
    features: [
      {
        href: 'https://',
        name: 'Navigate tenants, namespaces, and topics.',
        tiers: {
          free: { type: 'boolean', value: true },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: true },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Create and delete resources.',
        tiers: {
          free: { type: 'boolean', value: true },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: true },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'View Topic Stats',
        tiers: {
          free: { type: 'boolean', value: true },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: true },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Manage Namespace Bundles',
        tiers: {
          free: { type: 'boolean', value: false },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: false },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Manage Topic Compaction',
        tiers: {
          free: { type: 'boolean', value: false },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: false },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Manage Tiered Storage',
        tiers: {
          free: { type: 'boolean', value: false },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: false },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Manage Pulsar Functions (planned)',
        tiers: {
          free: { type: 'boolean', value: false },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: false },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Manage Sources and Sinks (planned)',
        tiers: {
          free: { type: 'boolean', value: false },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: false },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Manage Pulsar SQL (planned)',
        tiers: {
          free: { type: 'boolean', value: false },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: false },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
    ],
  },
  {
    name: 'Namespace and Topic Policies Management',
    isGroupFeature: true,
    features: [
      {
        href: 'https://',
        name: 'Namespace and Topic Policies Management',
        tiers: {
          free: { type: 'boolean', value: true },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: true },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
    ],
  },
  {
    name: 'Schema Management',
    isGroupFeature: true,
    features: [
      {
        href: 'https://',
        name: 'Schema Management',
        tiers: {
          free: { type: 'boolean', value: true },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: true },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
    ],
  },
  {
    name: 'Consume Data',
    features: [
      {
        href: 'https://',
        name: 'Basic Message Filters',
        tiers: {
          free: { type: 'boolean', value: true },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: true },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'JavaScript Message Filters',
        tiers: {
          free: { type: 'boolean', value: true },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: true },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Map Message Fields to Table Columns',
        tiers: {
          free: { type: 'boolean', value: true },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: true },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Consume Compacted Topic',
        tiers: {
          free: { type: 'boolean', value: true },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: true },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Consumer Session State',
        tiers: {
          free: { type: 'boolean', value: true },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: true },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Consume From Multiple Topics',
        tiers: {
          free: { type: 'boolean', value: false },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: false },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Set Colorization Rules',
        tiers: {
          free: { type: 'boolean', value: false },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: false },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Export Consumed Data to CSV or JSON',
        tiers: {
          free: { type: 'boolean', value: false },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: false },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Search Consumed Data (planned)',
        tiers: {
          free: { type: 'boolean', value: false },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: false },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Visualize Consumed Data (planned)',
        tiers: {
          free: { type: 'boolean', value: false },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: false },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
    ],
  },
  {
    name: 'Produce Data',
    features: [
      {
        href: 'https://',
        name: 'Produce Single Message',
        tiers: {
          free: { type: 'boolean', value: true },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: true },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Message Generators',
        tiers: {
          free: { type: 'boolean', value: true },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: true },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Build Complex Producer Scenarios (planned)',
        tiers: {
          free: { type: 'boolean', value: false },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: false },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Reprocess Specific Messages (planned)',
        tiers: {
          free: { type: 'boolean', value: false },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: false },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
    ],
  },
  {
    name: 'Library',
    features: [
      {
        href: 'https://',
        name: 'Save and reuse Message Filters, Consumer Sessions, and other items.',
        tiers: {
          free: { type: 'boolean', value: true },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: true },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Add Markdown documentation to Tenant, Namespaces, and Topics.',
        tiers: {
          free: { type: 'boolean', value: true },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: true },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Set the context where these items are available.',
        tiers: {
          free: { type: 'boolean', value: true },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: true },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Share Library items with team-mates.',
        tiers: {
          free: { type: 'boolean', value: false },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: false },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
    ],
  },
  {
    name: 'Security',
    features: [
      {
        href: 'https://',
        name: 'Manage Pulsar ACLs',
        tiers: {
          free: { type: 'boolean', value: true },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: true },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Authenticate to Pulsar Instance',
        tiers: {
          free: { type: 'boolean', value: false },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: false },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Access Control (planned)',
        tiers: {
          free: { type: 'boolean', value: false },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: false },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Data Masking Rules (planned)',
        tiers: {
          free: { type: 'boolean', value: false },
          se: { type: 'boolean', value: false },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: false },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Offline Licensing',
        tiers: {
          free: { type: 'boolean', value: false },
          se: { type: 'boolean', value: false },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: false },
          dp: { type: 'boolean', value: false },
        },
        description: '',
      },
    ],
  },
  {
    name: 'Monitoring',
    features: [
      {
        href: 'https://',
        name: 'Visualize Pulsar Metrics (planned)',
        tiers: {
          free: { type: 'boolean', value: false },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: false },
          dp: { type: 'boolean', value: false },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Set Pulsar Metrics Alerts (planned)',
        tiers: {
          free: { type: 'boolean', value: false },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: false },
          dp: { type: 'boolean', value: false },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Proactive Data Monitoring (planned)',
        tiers: {
          free: { type: 'boolean', value: false },
          se: { type: 'boolean', value: false },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: false },
          dp: { type: 'boolean', value: false },
        },
        description: '',
      },
    ],
  },
  {
    name: 'Support',
    features: [
      {
        href: 'https://',
        name: 'Community',
        tiers: {
          free: { type: 'boolean', value: true },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: true },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: '24/7',
        tiers: {
          free: { type: 'boolean', value: false },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: false },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
    ],
  },
  {
    name: 'Managed Cloud Compatibility',
    features: [
      {
        href: 'https://',
        name: 'StreamNative Cloud',
        tiers: {
          free: { type: 'boolean', value: true },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: false },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
      {
        href: 'https://',
        name: 'Astra Streaming',
        tiers: {
          free: { type: 'boolean', value: true },
          se: { type: 'boolean', value: true },
          ee: { type: 'boolean', value: true },
          df: { type: 'boolean', value: false },
          dp: { type: 'boolean', value: true },
        },
        description: '',
      },
    ],
  },
];
